export enum NotesTypes {
  NOTE_CREATE = 'NOTE_CREATE',
  NOTES_LISTS = 'NOTES_LISTS',
  NOTE_LIST = 'NOTE_LIST',
  NOTE_DELETE = 'NOTE_DELETE',
  NOTE_EDIT = 'NOTE_EDIT',
  NOTE_COMMENT = 'NOTE_COMMENT',
  DELETE_COMMENT = 'DELETE_COMMENT',
}

export enum TodosTypes {
	CREATE_TODOS = 'CREATE_TODOS',
	LISTS_TODOS = 'LISTS_TODOS',
	LISTS_TODO = 'LISTS_TODO',
	EDIT_TODOS = 'EDIT_TODOS',
	DELETE_TODOS = 'DELETE_TODOS',
	TOGGLE_TODOS = 'TOGGLE_TODOS',
}