export enum NotesTypes {
  NOTE_CREATE = 'NOTE_CREATE',
  NOTES_LISTS = 'NOTES_LISTS',
  NOTE_LIST = 'NOTE_LIST',
  NOTE_DELETE = 'NOTE_DELETE',
  NOTE_EDIT = 'NOTE_EDIT',
  NOTE_COMMENT = 'NOTE_COMMENT',
  DELETE_COMMENT = 'DELETE_COMMENT',
}

export enum UserTypes {
  SIGN_IN = 'SIGN_IN',
	SIGN_UP = 'SIGN_UP',
	SIGN_OUT = 'SIGN_OUT',
	GET_USERS = 'GET_USERS',
  GET_USER = 'GET_USER',
	FOLLOW_USER = 'FOLLOW_USER',
	UNFOLLOW_USER = 'UNFOLLOW_USER',
}